[package]
name = "music-metadata-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
audiotags = "0.5.0"
id3 = "1.14.0"
image = "0.25.2"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.128"
